name: Prints and Gifts Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      id-token: write 
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENTID }}
        tenant-id: ${{ secrets.TENANTID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}

    - name: Upload files to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
          app-name: 'printsandgifts'
          package: ./
          