name: Prints and Gifts Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload files to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
          app-name: 'printsandgifts'
          package: ./
          